### ISSUE TITLE
 Quote: There's No CTRL+Z in The Life , So Apt-get update your life !

### ISSUE THREAD

**Issue by 0thm4n3** [jarmo/hackersays#39]
Quote : There's No CTRL+Z in The Life ,
So Apt-get update your life !

**Comment by jarmo** [comment]
I'm not sure what to think of this quote. As I understand it's made up by yourself? I don't see any originality nor humour in this quote. In addition it doesn't make sense at all because `apt-get update` does not update installed software so there's no new features after this command in any software.

We try to keep quality of the quotes high, that's why we're not accepting just any quote. I hope you understand and thanks for trying though!
